[workspace]
members = ['fivee', 'common', 'system_startup', 'system_ui']
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = "0.11.2"
glam = "0.24.1"
mapgen = "0.6.0"
rand = "0.8.5"
array2d = "0.3.0"