# name of the statblock
name = "Default"

# max number of hitpoints, 
# if not set: the entity cannot be damaged
hit_points = 10

# initiative modifier, 
# if not set: the entity has no initiative and does not receive a turn during a round
initiative = 0

# speed in feet
speed = 30

# number of actions that an entity can perform per turn
actions = 1
